Support device region parameter
Magic-Pod/bitrise-step-magicpod-uitest pull request #1
Opened 2019-04-27 07:41 UTC by NozomiIto

2019-04-27 07:42 UTC, NozomiIto commented
This should be published after magic-pod.com supports device_region parameter

2019-04-27 08:27 UTC, nkns165 commented on step.yml
> +  - device_region: "Default"
I'm not sure, but maybe you have to add "Default" also in `value_options`.
You can confirm the actual behavior by the procedure noted [here](https://github.com/NozomiIto/magic-pod/blob/develop/docs/development_tips/bitrise_step.md#check-ui-on-bitriseio)

2019-04-27 08:28 UTC, nkns165 requested changes
Reviewed. I'd appreciate if you check the behavior of default value.

2019-04-28 02:58 UTC, nkns165 approved these changes

2019-04-28 02:58 UTC, merged