Support test case numbers
Magic-Pod/bitrise-step-magicpod-uitest pull request #7
Opened 2020-02-24 02:50 UTC by NozomiIto

(and small refactoring)

2020-02-24 12:37 UTC, nkns165 requested changes
Sorry to be late, reviewed

2020-02-24 12:37 UTC, nkns165 commented on step.yml
> +      title: "Test Casd Numbers"
There's typo `Casd`.
And I think "Test case numbers" is better, as other parameter names.

2020-02-25 01:41 UTC, nkns165 approved these changes

2020-02-25 01:41 UTC, merged

2020-02-25 01:48 UTC, NozomiIto commented
I have not checked the UI on the Bitrise UI yet due to Bitrise trouble or something...

2020-02-25 02:25 UTC, nkns165 commented
😢

2020-02-25 05:15 UTC, NozomiIto commented
https://github.com/bitrise-io/bitrise-steplib/pull/2407